---
os: linux
dist: xenial
language: ruby
cache: bundler
jobs:
  include:
  - &acceptance
    env: PLATFORMS=deb_puppet6
    rvm: 2.5.7
    services: docker
    before_script:
    - |
      set -x
      git clone --depth 1 https://github.com/puppetlabs/puppetlabs-motd puppetlabs-motd
      cd puppetlabs-motd
      echo "gem 'bolt', require: false, git: 'https://github.com/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}', branch: '${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}'" >> Gemfile
      # override travis' defaults
      unset BUNDLE_GEMFILE
      bundle config gemfile ./Gemfile
      bundle config path '../vendor/bundle'
      bundle config with development
      bundle install --jobs 4 --retry 2
      bundle exec rake spec_prep
      bundle exec rake 'litmus:provision_list[default]'
      bundle exec rake 'litmus:install_agent'
      bundle exec rake 'litmus:install_module'
      bundle exec rake 'litmus:install_module'
      bundle exec rake 'litmus:install_modules_from_directory[./spec/fixtures/modules]'
      bundle exec rake 'litmus:add_feature[test_123]'
      set +x
    script:
    - bundle exec rake litmus:acceptance:parallel
    - bundle exec rake litmus:tear_down
  - <<: *acceptance
    rvm: 2.7